// Trade-specific description prompts to help clients provide useful details.
// Each hint is a short phrase the client can tap to append to their description.
// Sources: common quoting requirements from Australian trade associations (HIA, MBA, MPAQ).

export const JOB_DESCRIPTION_HINTS: Record<string, string[]> = {
  Cleaner: [
    'Mop floors',
    'Wipe down surfaces',
    'Vacuum carpets',
    'Clean bathrooms',
    'Kitchen deep clean',
    'Window cleaning',
    'Oven and rangehood',
    'End of lease clean',
    'Office clean',
    'Dust and polish',
    'Rubbish removal',
    'Steam clean carpets',
  ],
  Plumber: [
    'Leaking tap',
    'Blocked drain',
    'Hot water system',
    'Toilet repair',
    'Gas fitting',
    'Burst pipe',
    'New tap install',
    'Pipe replacement',
    'Backflow prevention',
    'Sewer repair',
  ],
  Electrician: [
    'Switchboard upgrade',
    'Power points',
    'Ceiling fan',
    'Smoke alarms',
    'LED downlights',
    'Safety switch',
    'Rewiring',
    'Outdoor lighting',
    'EV charger',
    'Data cabling',
  ],
  Builder: [
    'Granny flat',
    'Wall removal',
    'Deck build',
    'Pergola',
    'Extension',
    'Renovation',
    'Council approved',
    'Knock down rebuild',
    'Structural repair',
    'Retaining wall',
  ],
  Painter: [
    'Interior walls',
    'Ceilings',
    'Exterior repaint',
    'Feature wall',
    'Weatherboard',
    'Brick render',
    'Doors and trim',
    'Spray paint',
    'Colour consultation',
    'Prep and sand',
  ],
  Landscaper: [
    'New turf',
    'Garden beds',
    'Retaining wall',
    'Irrigation',
    'Tree removal',
    'Paving',
    'Mulching',
    'Hedge trimming',
    'Garden design',
    'Lawn mowing',
  ],
  Carpenter: [
    'Built-in wardrobe',
    'Timber deck',
    'Door replacement',
    'Skirting boards',
    'Pergola',
    'Custom shelving',
    'Window frames',
    'Stair repair',
    'Timber flooring',
    'Gate build',
  ],
  Roofer: [
    'Roof leak',
    'Full replacement',
    'Gutter clean',
    'Downpipes',
    'Ridge capping',
    'Tile repair',
    'Colorbond',
    'Roof inspection',
    'Flashing repair',
    'Skylight install',
  ],
  Tiler: [
    'Bathroom tiles',
    'Kitchen splashback',
    'Floor tiles',
    'Outdoor patio',
    'Waterproofing',
    'Tile repair',
    'Mosaic feature',
    'Grout replacement',
    'Wall tiles',
    'Tiles supplied',
  ],
  Concreter: [
    'Driveway slab',
    'Shed slab',
    'Concrete path',
    'Exposed aggregate',
    'Coloured concrete',
    'Old concrete removal',
    'Retaining wall',
    'Steps and stairs',
    'Pool surround',
    'Stamped finish',
  ],
  HVAC: [
    'Split system',
    'Ducted service',
    'Not cooling',
    'Not heating',
    'Multi-head system',
    'Gas heating',
    'Filter clean',
    'New install',
    'Thermostat',
    'Refrigerant top-up',
  ],
  Pest: [
    'Termite inspection',
    'Cockroach treatment',
    'Ant treatment',
    'Rodent control',
    'Spider spray',
    'Pre-purchase report',
    'Bee removal',
    'Flea treatment',
    'Possum removal',
    'Bed bugs',
  ],
  Locksmith: [
    'Locked out',
    'Rekey locks',
    'Deadbolt install',
    'Smart lock',
    'Window locks',
    'Master key system',
    'Safe opening',
    'Lock replacement',
    'Garage lock',
    'Emergency entry',
  ],
  Fencer: [
    'Colorbond fence',
    'Timber paling',
    'Pool fence',
    'Gate install',
    'Old fence removal',
    'Retaining wall',
    'Slat screen',
    'Chain wire',
    'Post replacement',
    'Fence repair',
  ],
  Bricklayer: [
    'Letterbox build',
    'Brick repair',
    'Repointing',
    'Retaining wall',
    'Extension wall',
    'Render over brick',
    'Feature wall',
    'Garden wall',
    'Chimney repair',
    'Block wall',
  ],
  'Pool Builder': [
    'Concrete pool',
    'Fibreglass pool',
    'Pool resurface',
    'Pool fencing',
    'Pump and filter',
    'Pool heating',
    'Spa install',
    'Green pool cleanup',
    'Pool cover',
    'Tile repair',
  ],
  Bathroom: [
    'Full renovation',
    'Shower screen',
    'Vanity upgrade',
    'Waterproofing',
    'Tiling',
    'Bath to shower',
    'Tapware replace',
    'Mirror install',
    'Heated towel rail',
    'Exhaust fan',
  ],
  Kitchen: [
    'Full renovation',
    'Benchtop replace',
    'New cabinetry',
    'Splashback',
    'Appliance install',
    'Demolition',
    'Sink and tap',
    'Rangehood',
    'Pantry build',
    'Lighting upgrade',
  ],
  Renovation: [
    'Bathroom',
    'Kitchen',
    'Living area',
    'Structural changes',
    'Cosmetic refresh',
    'Heritage home',
    'Council approved',
    'Full house',
    'Single room',
    'Open plan conversion',
  ],
  Demolition: [
    'Internal strip-out',
    'Full house demo',
    'Asbestos removal',
    'Shed removal',
    'Pool demolition',
    'Concrete removal',
    'Wall removal',
    'Bathroom strip',
    'Kitchen strip',
    'Rubbish disposal',
  ],
  Excavation: [
    'Site cut',
    'Trenching',
    'Pool dig',
    'Driveway',
    'Soil removal',
    'Rock breaking',
    'Stump removal',
    'Levelling',
    'Drainage',
    'Bobcat work',
  ],
  'Air Conditioning': [
    'Split system',
    'Ducted system',
    'Not cooling',
    'Not heating',
    'New install',
    'Gas heating',
    'Service and clean',
    'Multi-head',
    'Thermostat',
    'Evaporative cooling',
  ],
  'Pest Control': [
    'Termite inspection',
    'Cockroach treatment',
    'Ant treatment',
    'Rodent control',
    'Spider spray',
    'Pre-purchase report',
    'Flea treatment',
    'Possum removal',
    'Bee removal',
    'Bed bugs',
  ],
  Pool: [
    'Concrete pool',
    'Fibreglass pool',
    'Pool resurface',
    'Pool fencing',
    'Pump and filter',
    'Pool heating',
    'Green pool cleanup',
    'Salt chlorinator',
    'Pool cover',
    'Tile repair',
  ],
  Handyman: [
    'Furniture assembly',
    'Hang TV',
    'Shelving install',
    'Door repair',
    'Window repair',
    'Plaster patching',
    'Tap washer',
    'Picture hanging',
    'Blind install',
    'Odd jobs',
  ],
  Glazier: [
    'Broken window',
    'Shower screen',
    'Double glazing',
    'Mirror install',
    'Glass splashback',
    'Sliding door',
    'Window replacement',
    'Safety glass',
    'Cat flap',
    'Shopfront glass',
  ],
  Plasterer: [
    'Patch holes',
    'Re-plaster room',
    'Cornice install',
    'Ceiling repair',
    'Water damage',
    'Skim coat',
    'Ornamental work',
    'Crack repair',
    'Set and sand',
    'New walls',
  ],
  Renderer: [
    'Cement render',
    'Acrylic render',
    'Texture coat',
    'Crack repair',
    'Brick render',
    'Block render',
    'Colour through',
    'Paint over',
    'Exterior walls',
    'Feature finish',
  ],
  'Flooring Specialist': [
    'Sand and polish',
    'Timber install',
    'Laminate',
    'Vinyl plank',
    'Carpet replace',
    'Floor levelling',
    'Stain and coat',
    'Subfloor repair',
    'Skirting boards',
    'Stair treads',
  ],
  'Cabinet Maker': [
    'Custom wardrobe',
    'Kitchen cabinetry',
    'Bathroom vanity',
    'Entertainment unit',
    'Laundry cabinets',
    'Timber finish',
    'Laminate finish',
    'Bookcase',
    'Study desk',
    'Walk-in robe',
  ],
  Solar: [
    'Solar panels',
    'Battery storage',
    'System size',
    'Inverter replace',
    'Solar hot water',
    'Roof mount',
    'EV charger combo',
    'Monitoring system',
    'Panel clean',
    'System upgrade',
  ],
  Waterproofing: [
    'Bathroom membrane',
    'Balcony',
    'Basement',
    'Shower leak',
    'Retaining wall',
    'Roof coating',
    'Deck membrane',
    'Planter box',
    'Wet area',
    'Subfloor',
  ],
  Insulation: [
    'Ceiling batts',
    'Blown-in',
    'Wall insulation',
    'Underfloor',
    'Soundproofing',
    'Thermal barrier',
    'Roof sarking',
    'Existing home',
    'New build',
    'Removal and replace',
  ],
  'Garage Doors': [
    'New door install',
    'Roller door',
    'Panel lift',
    'Motor replace',
    'Off track',
    'Remote program',
    'Single door',
    'Double door',
    'Spring replace',
    'Weatherseal',
  ],
  'Security Systems': [
    'CCTV cameras',
    'Alarm system',
    'Video doorbell',
    'Intercom',
    'Access control',
    'Motion sensors',
    'Smart home',
    'Monitoring setup',
    'Wired system',
    'Wireless system',
  ],
  'Appliance Repair': [
    'Washing machine',
    'Fridge repair',
    'Dishwasher',
    'Oven repair',
    'Dryer repair',
    'Microwave',
    'Rangehood',
    'Ice maker',
    'Error code',
    'Not turning on',
  ],
  'Private Chef': [
    'Dinner party',
    'Meal prep',
    'Special occasion',
    'Dietary needs',
    'Multi-course',
    'Casual dining',
    'Brunch',
    'Kids party food',
    'Weekly service',
    'Ingredients included',
  ],
  'Event Catering': [
    'Wedding',
    'Corporate event',
    'Birthday party',
    'Buffet style',
    'Sit-down meal',
    'Grazing table',
    'Dietary needs',
    'Drinks service',
    'At-home event',
    'Venue catering',
  ],
};

// Fallback hints for trades not in the map
export const DEFAULT_JOB_HINTS = [
  'Repair',
  'Install',
  'Replace',
  'Inspection',
  'Urgent',
  'Indoor',
  'Outdoor',
  'Quote only',
];

/**
 * Get description hints for a given trade category.
 */
export function getJobHints(category: string | null): string[] {
  if (!category) return DEFAULT_JOB_HINTS;
  // Direct match first
  if (JOB_DESCRIPTION_HINTS[category]) return JOB_DESCRIPTION_HINTS[category];
  // Case-insensitive fallback
  const key = Object.keys(JOB_DESCRIPTION_HINTS).find(
    (k) => k.toLowerCase() === category.toLowerCase()
  );
  return key ? JOB_DESCRIPTION_HINTS[key] : DEFAULT_JOB_HINTS;
}
