-- ---------------------------------------------------------------------------
-- Seed: Initial keyword suggestions for common recurring service types
-- These provide immediate suggestions before organic data accumulates.
-- ---------------------------------------------------------------------------

INSERT INTO service_description_keywords (service_type, keyword, frequency) VALUES
-- Cleaning
('Regular Domestic Clean', 'vacuum', 10),
('Regular Domestic Clean', 'mopping', 10),
('Regular Domestic Clean', 'dusting', 9),
('Regular Domestic Clean', 'bathrooms', 9),
('Regular Domestic Clean', 'kitchen surfaces', 8),
('Regular Domestic Clean', 'skirting boards', 7),
('Regular Domestic Clean', 'cobwebs', 6),
('Regular Domestic Clean', 'window sills', 6),
('Regular Domestic Clean', 'bed linen change', 5),
('Regular Domestic Clean', 'bin emptying', 5),
('Deep Clean', 'oven clean', 10),
('Deep Clean', 'grout scrub', 9),
('Deep Clean', 'behind appliances', 8),
('Deep Clean', 'inside cupboards', 8),
('Deep Clean', 'exhaust fans', 7),
('Deep Clean', 'light fixtures', 7),
('Deep Clean', 'window tracks', 6),
('Deep Clean', 'mould treatment', 6),
('End of Lease Clean', 'bond clean', 10),
('End of Lease Clean', 'carpet steam', 9),
('End of Lease Clean', 'oven degreasing', 9),
('End of Lease Clean', 'window cleaning', 8),
('End of Lease Clean', 'wall marks', 7),
('End of Lease Clean', 'garage sweep', 6),
('Office Clean', 'desk wipe-down', 10),
('Office Clean', 'floor vacuum', 9),
('Office Clean', 'kitchen sanitise', 8),
('Office Clean', 'bathroom restock', 8),
('Office Clean', 'bin emptying', 7),
('Office Clean', 'glass partitions', 6),
('Commercial Clean', 'floor polishing', 9),
('Commercial Clean', 'sanitisation', 9),
('Commercial Clean', 'high traffic areas', 8),
('Commercial Clean', 'waste disposal', 7),
('Commercial Clean', 'reception area', 6),

-- Lawn & Garden
('Regular Lawn Mow', 'front yard', 10),
('Regular Lawn Mow', 'back yard', 10),
('Regular Lawn Mow', 'edging', 9),
('Regular Lawn Mow', 'clippings removal', 8),
('Regular Lawn Mow', 'nature strip', 7),
('Regular Lawn Mow', 'blow paths', 6),
('Lawn Mow & Edge', 'whipper snip', 10),
('Lawn Mow & Edge', 'edging', 9),
('Lawn Mow & Edge', 'garden beds', 8),
('Lawn Mow & Edge', 'driveway blow', 7),
('Full Garden Maintenance', 'weeding', 10),
('Full Garden Maintenance', 'pruning', 9),
('Full Garden Maintenance', 'mulching', 9),
('Full Garden Maintenance', 'hedge trimming', 8),
('Full Garden Maintenance', 'fertilising', 7),
('Full Garden Maintenance', 'plant health check', 6),
('Full Garden Maintenance', 'green waste removal', 6),
('Hedge Trimming', 'height reduction', 9),
('Hedge Trimming', 'shape maintenance', 8),
('Hedge Trimming', 'green waste removal', 7),
('Hedge Trimming', 'boundary hedges', 6),

-- Pool & Spa
('Regular Pool Clean', 'leaf scoop', 10),
('Regular Pool Clean', 'filter basket', 9),
('Regular Pool Clean', 'chemical balance', 9),
('Regular Pool Clean', 'brush walls', 8),
('Regular Pool Clean', 'vacuum floor', 8),
('Regular Pool Clean', 'water level check', 7),
('Pool Chemical Balance', 'chlorine', 10),
('Pool Chemical Balance', 'pH testing', 10),
('Pool Chemical Balance', 'alkalinity', 8),
('Pool Chemical Balance', 'salt level', 7),
('Pool Chemical Balance', 'stabiliser', 6),
('Pool Filter Service', 'cartridge clean', 10),
('Pool Filter Service', 'backwash', 9),
('Pool Filter Service', 'pressure check', 8),
('Pool Filter Service', 'media replacement', 6),

-- Pest Control
('General Pest Control', 'cockroaches', 10),
('General Pest Control', 'spiders', 10),
('General Pest Control', 'ants', 9),
('General Pest Control', 'internal spray', 8),
('General Pest Control', 'external barrier', 8),
('General Pest Control', 'roof void', 7),
('General Pest Control', 'subfloor', 6),
('Termite Inspection', 'moisture readings', 10),
('Termite Inspection', 'thermal imaging', 9),
('Termite Inspection', 'subfloor access', 8),
('Termite Inspection', 'garden beds', 7),
('Termite Inspection', 'fence posts', 6),

-- Window Cleaning
('Interior Windows', 'glass polish', 10),
('Interior Windows', 'frame wipe', 9),
('Interior Windows', 'sill clean', 8),
('Interior Windows', 'fly screens', 7),
('Exterior Windows', 'squeegee', 10),
('Exterior Windows', 'frame wash', 9),
('Exterior Windows', 'cobweb removal', 8),
('Exterior Windows', 'second storey', 7),
('Interior & Exterior Windows', 'full window clean', 10),
('Interior & Exterior Windows', 'track cleaning', 9),
('Interior & Exterior Windows', 'screen wash', 8),

-- Carpet & Flooring
('Carpet Steam Clean', 'hot water extraction', 10),
('Carpet Steam Clean', 'stain treatment', 9),
('Carpet Steam Clean', 'deodorising', 8),
('Carpet Steam Clean', 'high traffic areas', 7),
('Carpet Steam Clean', 'drying time', 6),
('Tile & Grout Clean', 'grout scrub', 10),
('Tile & Grout Clean', 'tile polish', 9),
('Tile & Grout Clean', 'grout sealing', 8),
('Tile & Grout Clean', 'mould removal', 7),

-- Air Conditioning
('Split System Service', 'filter clean', 10),
('Split System Service', 'coil wash', 9),
('Split System Service', 'drain check', 8),
('Split System Service', 'gas pressure', 7),
('Split System Service', 'remote test', 6),
('Ducted System Service', 'duct inspection', 10),
('Ducted System Service', 'filter replacement', 9),
('Ducted System Service', 'zone check', 8),
('Ducted System Service', 'thermostat calibration', 7),
('Full HVAC Service', 'heating test', 10),
('Full HVAC Service', 'cooling test', 9),
('Full HVAC Service', 'vent cleaning', 8),
('Full HVAC Service', 'refrigerant check', 7),

-- Handyman
('General Maintenance', 'door adjustment', 9),
('General Maintenance', 'tap washer', 9),
('General Maintenance', 'silicone reseal', 8),
('General Maintenance', 'touch-up paint', 7),
('General Maintenance', 'light globe change', 7),
('General Maintenance', 'fence repair', 6),
('Safety Checks', 'smoke alarms', 10),
('Safety Checks', 'deadlocks', 9),
('Safety Checks', 'window locks', 8),
('Safety Checks', 'handrails', 7),
('Safety Checks', 'trip hazards', 6),

-- Gutter Cleaning
('Gutter Clean', 'debris removal', 10),
('Gutter Clean', 'downpipe flush', 9),
('Gutter Clean', 'gutter guard check', 8),
('Gutter Clean', 'roof valley clear', 7),
('Gutter Clean', 'fascia inspection', 6),

-- Plumbing
('Plumbing Inspection', 'tap check', 10),
('Plumbing Inspection', 'toilet flush test', 9),
('Plumbing Inspection', 'hot water check', 8),
('Plumbing Inspection', 'pipe inspection', 7),
('Plumbing Inspection', 'drain flow test', 7),
('Plumbing Inspection', 'water pressure', 6),

-- Electrical
('Electrical Safety Inspection', 'switchboard check', 10),
('Electrical Safety Inspection', 'RCD testing', 10),
('Electrical Safety Inspection', 'smoke alarm test', 9),
('Electrical Safety Inspection', 'power point check', 8),
('Electrical Safety Inspection', 'earth leakage', 7),

-- Fire Safety
('Fire Safety Inspection', 'smoke alarm test', 10),
('Fire Safety Inspection', 'extinguisher check', 10),
('Fire Safety Inspection', 'exit light test', 9),
('Fire Safety Inspection', 'fire door inspection', 8),
('Fire Safety Inspection', 'evacuation plan review', 7),

-- Solar
('Solar Panel Clean', 'panel wash', 10),
('Solar Panel Clean', 'inverter check', 9),
('Solar Panel Clean', 'output monitoring', 8),
('Solar Panel Clean', 'bird proofing', 7),
('Solar Panel Clean', 'wiring inspection', 6)

ON CONFLICT (service_type, keyword)
DO UPDATE SET frequency = GREATEST(service_description_keywords.frequency, EXCLUDED.frequency);
